Documentation: Fix etcdctl tx eBNF
`create` also expects operand, or this error is printed:
Error:  malformed comparison: create("mykey") "0"; got create("mykey") "0" ""